[package]
name = "analytic"
version = "0.1.0"
authors = ["Yuping Luo <roosephu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
rug = "1.11.0"
num = "0.3.1"
rustfft = "5.0.1"
GSL = "3.0.0"
bit-vec = "0.6.3"
log = "0.4.14"
env_logger = "0.8.3"
num-traits = "0.2.14"
num-complex = "0.3"
rand = "0.8.3"
