[package]
name = "analytic"
version = "0.1.0"
authors = ["Yuping Luo <roosephu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.11.0"
num = "0.3.1"
