[package]
name = "f64xn-impl-func"
authors = ["Yuping Luo <roosephu@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rug = "1.14.0"
syn = "1.0.84"
quote = "1.0.10"
proc-macro2 = "1.0.36"
