[package]
name = "f64xn-impl-arith"
version = "0.1.0"
authors = ["Yuping Luo <roosephu@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.82", features = ["full"] }
quote = "1.0.10"
proc-macro2 = "1.0.34"
